---

- hosts: master
  become: true
  vars_files: vars.yml
  roles:
    - install_packages
    - install_pgsql
    - install_barman-cli
    - configure_master

- hosts: slave
  become: true
  vars_files: vars.yml
  roles:
    - install_packages
    - install_pgsql
    - configure_standby

- hosts: backup
  become: true
  vars_files: vars.yml
  roles:
    - install_packages
    - install_pgsql
    - install_barman
    - configure_barman