Vagrant.configure("2") do |config|
config.vbguest.auto_update = false

 config.vm.box = "centos/7"
 config.vm.network "private_network", ip: "192.168.33.17"
 config.vm.synced_folder ".", "/vagrant"
    

 config.vm.provider "virtualbox" do |vb|
      vb.name = "host1"  
      vb.gui = true
      vb.memory = "2024"
   end
 
   config.vm.provision "shell", inline: <<-SHELL
     
mkdir -p ~root/.ssh
cp ~vagrant/.ssh/auth* ~root/.ssh
hostnamectl set-hostname host1
sed -i "s/SELINUX=enforcing/SELINUX=disabled/" /etc/selinux/config
mv /etc/localtime /etc/localtime.bak
ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime
#firewall-cmd --permanent --new-service=zabbix
#firewall-cmd --permanent --service=zabbix --add-port=10050/tcp
#firewall-cmd --permanent --service=zabbix --set-short="Zabbix Agent"
#firewall-cmd --permanent --add-service=zabbix
#firewall-cmd --reload
rpm -i https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-1.el7.noarch.rpm
yum makecache
yum install -y zabbix-agent
# Закомментируем старые параметры:
sed -i '98s/^/#/' /etc/zabbix/zabbix_agentd.conf
sed -i '139s/^/#/' /etc/zabbix/zabbix_agentd.conf
sed -i '150s/^/#/' /etc/zabbix/zabbix_agentd.conf
# Добавим новые параметры:
sed -i '99i Server=192.168.33.14' /etc/zabbix/zabbix_agentd.conf
sed -i '140i ServerActive=192.168.33.14' /etc/zabbix/zabbix_agentd.conf
sed -i '151i Hostname=host1' /etc/zabbix/zabbix_agentd.conf
systemctl restart zabbix-agent
systemctl enable zabbix-agent
SHELL
end

