# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
   config.vm.box = "centos/7"
   config.vm.box_check_update = false
   #config.vm.network "forwarded_port", guest: 80, host: 8080
   #config.vm.synced_folder ".", "/vagrant"
 
   config.vm.define "docker", primary: true do |s|
     s.vm.hostname = 'docker'
     s.vm.network "private_network", ip: "192.168.111.100"
     s.vm.provision "shell", inline: <<-SHELL
        
        ## Пример установки Docker в Vagrant
         
        # Отключаем или настраиваем selinux
        sed -i "s/SELINUX=enforcing/SELINUX=disabled/" /etc/selinux/config
        
        # Устаналиваем и настриваем docker
        yum check-update
        curl -fsSL https://get.docker.com/ | sh
        systemctl start docker
        systemctl enable docker
        
        # Добавляем пользователя (vagrant) в группу docker, команды будут выполняться от него вместо root 
        usermod -aG docker vagrant

        # Проверка docker
        docker run hello-world

        # Скачиваем образ Linux Alpine
        # docker pull alpine

        # Создаем каталог и копируем в него Dockerfile для установки nginx и конфиги:
        mkdir -p /var/docker/alpine/nginx
        cp -r /vagrant/install_nginx/* /var/docker/alpine/nginx

        # Запускаем установку nginx из Dockerfile  
        docker build -t alpine-nginx /var/docker/alpine/nginx/
        docker run alpine-nginx

     SHELL
   end
 end