
Vagrant.configure("2") do |config|
config.vbguest.auto_update = false

 config.vm.box = "centos/7"
 config.vm.network "private_network", ip: "192.168.33.10"
 config.vm.synced_folder ".", "/vagrant"

 config.vm.provider "virtualbox" do |vb|
      vb.name = "ipaserver.test.lab"  
      vb.gui = true
      vb.memory = "3024"

   end
 
   config.vm.provision "shell", inline: <<-SHELL
     
mkdir -p ~root/.ssh
cp ~vagrant/.ssh/auth* ~root/.ssh

# Отключим SELinux:
sed -i "s/SELINUX=enforcing/SELINUX=disabled/" /etc/selinux/config

# Отключим временно файервол, после установки включим обратно:
systemctl stop firewalld

# Синхронизируем время и установим часовой пояс Москвы:
# ntpdate 1.ru.pool.ntp.org
mv /etc/localtime /etc/localtime.bak
ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime

# Назначаем полное имя (FQDN) серверу "ipaserver.test.lab" (требование FreeIPA):
hostnamectl set-hostname ipaserver.test.lab

# Поскольку DNS-сервера нет, в /etc/hosts укажем ip и имя сервера FreeIPA и клиентского хоста:
echo -e "192.168.33.14 host1.test.lab host1" >> /etc/hosts
echo -e "192.168.33.10 ipaserver.test.lab ipaserver" >> /etc/hosts

# Устанавливаем epel-репозиторий и пакеты FreeIPA Server:
yum -y install epel-release
# yum -y update
yum -y install ipa-server

# Запускаем установку FreeIPA Server в режиме автоответа, передав необходимые параметры:
# -a password    #пароль учетной записи admin
# --hostname=ipaserver.test.lab   #FQDN имя сервера
# -r TEST.LAB  #Kerberos realm name (доменное имя большими буквами)
# -p password  #The kerberos master password 
# -n test.lab  #доменное имя
# -U  #установка в режиме автоответа 
ipa-server-install -a password --hostname=ipaserver.test.lab -r TEST.LAB -p password -n test.lab -U

# Настроим правила на файерволе (dns-опционально,т.к. не установлен):
systemctl start firewalld
firewall-cmd --permanent --add-service={ntp,http,https,ldap,ldaps,kerberos,kpasswd,dns}
firewall-cmd --reload

   SHELL
end

