# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {

:abr1 => {
        :box_name => "centos/7",
        :net => [
				   {ip: '192.168.20.10', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "vlan20"},
				   {ip: '192.168.30.10', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "vlan30"},
           {ip: '192.168.100.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "users-net"}
                ]
  },

:abr2 => {
      :box_name => "centos/7",
      :net => [
          {ip: '192.168.20.9', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "vlan20"},
          {ip: '192.168.40.9', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "vlan40"},
          {ip: '192.168.101.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "users-net"}
            ]
  },

:abr3 => {
      :box_name => "centos/7",
      :net => [
          {ip: '192.168.30.8', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "vlan30"},
          {ip: '192.168.40.8', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "vlan40"},
          {ip: '192.168.102.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "users-net"}
            ]
  },
	
}

Vagrant.configure("2") do |config|
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "vvv"
      ansible.playbook = "provisioning/playbook.yml"
      ansible.sudo = "true"
    end

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
		box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

		case boxname.to_s
		when "abr1"
			box.vm.provision "shell", inline: <<-SHELL
			SHELL
		when "abr2"
      box.vm.provision "shell", inline: <<-SHELL
			SHELL
		when "abr3"
			box.vm.provision "shell", inline: <<-SHELL
			SHELL
    end
 
  end

end
  
  
end
