# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/6",
        #:public => {:ip => '192.168.50.11', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
:inetRouter2 => {
	:box_name => "centos/7",
	# добавляем public-интерфейс, чтобы хостовая машина видела inetRouter2
	# :public => {:ip => '192.168.50.3', :adapter => 3},
	:net => [
			   {ip: '192.168.252.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net2"},
			]
},
:centralRouter => {
        :box_name => "centos/7",
        :net => [
				   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
				   {ip: '192.168.254.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
				   {ip: '192.168.253.1', adapter: 4, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 5, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.0.33', adapter: 6, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
				   {ip: '192.168.0.65', adapter: 7, netmask: "255.255.255.192", virtualbox__intnet: "wi-fi-net"},
				   {ip: '192.168.252.2', adapter: 8, netmask: "255.255.255.252", virtualbox__intnet: "router-net2"},
                ]
  },
  
:centralServer => {
		:box_name => "centos/7",
		# добавляем public-интерфейс, чтобы хостовая машина видела centralServer
		:public => {:ip => '192.168.50.12', :adapter => 4},
        :net => [
					{ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   # {adapter: 3, auto_config: false, virtualbox__intnet: true},
			       # {adapter: 4, auto_config: false, virtualbox__intnet: true},
                ]
 },
	
	
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
		box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

		box.vm.provision "shell", inline: <<-SHELL
		# для всех хостов выполнить команды
          		mkdir -p ~root/.ssh
				cp ~vagrant/.ssh/auth* ~root/.ssh
				yum install -y traceroute
        SHELL
        
		case boxname.to_s
		when "inetRouter"
			box.vm.provision "shell", inline: <<-SHELL
			setenforce 0 && sed -i "s/SELINUX=enforcing/SELINUX=disabled/" /etc/selinux/config 
			# Включить форвардинг пакетов
			echo -e 'net.ipv4.conf.all.forwarding=1\nnet.ipv4.ip_forward=1' >> /etc/sysctl.conf
			sysctl -p
			# Прописываем роутинг, чтобы пакеты, предназначенные внутренним ip-адресам направлялись от inetRouter к centraRouter (через шлюз  192.168.255.2) 
			# и далее уже разруливались с помощью таблицы маршрутизации CentralRouter
			echo "192.168.0.0/16 via 192.168.255.2" > /etc/sysconfig/network-scripts/route-eth1
			# Перезапустить сеть
			service network restart
			# Нам необходимо запретить доступ по ssh всем, кроме тех, кто знает «как правильно постучаться». 
			# Для ssh-доступа необходимо будет выполнить последовательное подключение к портам: 8881 7777 9991 в течении 30 сек.
			# Применяем правила iptables в скрипте
			chmod +x /vagrant/iptables_rules_inetRouter.sh
			bash /vagrant/iptables_rules_inetRouter.sh
			# Разрешаем вход по паролю на ssh-сервере
			sed -i '66s/^/#/' /etc/ssh/sshd_config
			sed -i '67i PasswordAuthentication yes' /etc/ssh/sshd_config
			service sshd restart 
			SHELL
		when "inetRouter2"
			box.vm.hostname = 'inetRouter2'
            box.vm.network 'forwarded_port', guest: 8080, host: 8080, host_ip: '127.0.0.1'
			box.vm.provision "shell", inline: <<-SHELL
			setenforce 0 && sed -i "s/SELINUX=enforcing/SELINUX=disabled/" /etc/selinux/config
			# Включить форвардинг пакетов
			echo -e 'net.ipv4.conf.all.forwarding=1\nnet.ipv4.ip_forward=1' >> /etc/sysctl.conf
			sysctl -p
			# Прописываем роутинг, чтобы пакеты, предназначенные внутренним ip-адресам направлялись от inetRouter2 к centraRouter (через шлюз  192.168.252.2) 
			# и далее уже разруливались с помощью таблицы маршрутизации CentralRouter
			echo "192.168.0.0/16 via 192.168.252.2" >  /etc/sysconfig/network-scripts/route-eth1
			# Перезапустить сеть
			service network restart
			# Настраиваем фаервол
			systemctl start firewalld
			systemctl enable firewalld
			# Добавить внешний сетевой интерфейс eth0 (inet) в зону public
			firewall-cmd --zone=public --change-interface=eth0
			# Добавить внутренний сетевой интерфейс eth1 (192.168.252.1) в зону internal
			firewall-cmd --zone=internal --change-interface=eth1
			# Добавить nat маскарадинг для зоны internal
			firewall-cmd --zone=internal --add-masquerade --permanent
			# Входящие запросы по tcp 8080 для зоны public перенапрвлять на 192.168.0.2:80
			firewall-cmd --zone=public --add-forward-port=port=8080:proto=tcp:toport=80:toaddr=192.168.0.2 --permanent
			# Применить правила фаеврола
			firewall-cmd --reload
			SHELL
		when "centralRouter"
			box.vm.provision "shell", inline: <<-SHELL
			setenforce 0 && sed -i "s/SELINUX=enforcing/SELINUX=disabled/" /etc/selinux/config
			# Устанавливаем nmap для работы скрипта knock.sh
			yum install -y nmap
			# Включить форвардинг пакетов
			echo -e 'net.ipv4.conf.all.forwarding=1\nnet.ipv4.ip_forward=1' >> /etc/sysctl.conf
			sysctl -p
			# Отключаем default gateway для интерфейса eth0 (Vagrant), чтобы пакеты не ходили в интернет через nat Vagrant
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
			# Указываем шлюз по умолчанию для интерфейса eth1 и eth7
			echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
			echo "GATEWAY=192.168.252.1" >> /etc/sysconfig/network-scripts/ifcfg-eth7
			# Прописываем роутинг, чтобы пакеты ходили от centralOffice в office1
			echo "192.168.2.0/24 via 192.168.254.2" >  /etc/sysconfig/network-scripts/route-eth1
			# Прописываем роутинг, чтобы пакеты ходили от centralOffice в office2
			echo "192.168.1.0/24 via 192.168.253.2" >> /etc/sysconfig/network-scripts/route-eth1
			# Перезапустить сеть
			systemctl restart network
			# Делаем скрипт knock.sh исполняемым. С помощью него будем подключаться по ssh inetRouter. 
			chmod +x /vagrant/knock.sh 
			SHELL
		when "centralServer"
			box.vm.provision "shell", inline: <<-SHELL
			setenforce 0 && sed -i "s/SELINUX=enforcing/SELINUX=disabled/" /etc/selinux/config
			# Удаляем маршрут из таблицы маршрутизации для интерфейса eth0 (Vagrant), чтобы исключить отправку пакетов на него
			# ip route del default via 10.0.2.2 dev eth0
			# Устанавливаем nginx 
			yum -y install epel-release && yum install -y nginx
			systemctl start nginx
			systemctl enable nginx 
			# Отключаем default gateway для интерфейса eth0 (Vagrant), чтобы пакеты не ходили в интернет через nat Vagrant
			echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
			# Указываем шлюз по умолчанию для интерфейса eth1
			echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
			# Перезапустить сеть
			systemctl restart network
			SHELL
		end
		 box.vm.provision "shell", inline: <<-SHELL
		# после поднятия каждого хоста в конце выполнить контрольный перезапуск сети, чтобы пофиксить проблему,
		# связанную с недоступностью серверов (приходилось перезапускать сеть на отдельных хостах вручную)
		/etc/init.d/network restart
        SHELL

      end

  end
  
end

