Vagrant.configure("2") do |config|
config.vbguest.auto_update = false

 config.vm.box = "centos/7"
 config.vm.network "private_network", ip: "192.168.33.14"
 config.vm.synced_folder ".", "/vagrant"
    

 config.vm.provider "virtualbox" do |vb|
      vb.name = "srv-zabbix"  
      vb.gui = true
      vb.memory = "2024"
   end
 
   config.vm.provision "shell", inline: <<-SHELL
     
mkdir -p ~root/.ssh
cp ~vagrant/.ssh/auth* ~root/.ssh
     



   SHELL
end

